Add placeholders for ctl and status
oreboot/oreboot pull request #464
Opened 2021-08-06 20:55 UTC by rminnich

ctl will be used instead of writing strings via write(),
which showed the value of control strings (to me) but
but the implementation is a kludge.

Further, we need to have build time checking of the strings,
and better rules around how it works.

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

2021-08-20 19:46 UTC, rminnich commented
gonna try this again based on nick's suggestions; I have a lot to learn about Rust. But the idea of breaking out ctl and stat is still something I want to do.

2021-10-01 17:52 UTC, rminnich commented on src/lib/consts/src/lib.rs
> +    TTY{Baud: Baud}
done

2021-10-01 20:57 UTC, orangecms commented on src/arch/x86/x86_64/Cargo.toml
> +consts = { path = "../../../lib/consts"}
That shouldn't be here... or should it? I wonder why CI wouldn't complain. Maybe anything can be put here without restrictive validation.

2021-10-01 21:21 UTC, orangecms requested changes
looks okay except for that tiny thing in the x86_64/Cargo.toml

2021-10-01 21:27 UTC, orangecms approved these changes

2021-10-01 21:41 UTC, merged