docs: Initial Crate level RustDoc for oreboot_nezha_bt0
oreboot/oreboot pull request #615
Opened 2022-10-28 03:03 UTC by bwerthmann

Initially, include path was `../../README.md`. However, in this configuration Cargo's change detection failed to invalidate artifact cache when the included document changes.

```rust
#![doc = include_str!("../../README.md")]
```

The fix is to:

1. make a symbolic link from `oreboot_nezha_bt0` src dir to document

    README.md -> ../../README.md

2. Set Crate level doc include path to symbolic link `README.md`

```rust
#![doc = include_str!("README.md")]
```

3. Build and Open RustDoc for `oreboot_nezha_bt0`

```bash
cd oreboot
cd src/mainboard/sunxi/nezha/bt0
cargo doc --document-private-items --open
```

```console
   Compiling oreboot-nezha-bt0 v0.1.0 (oreboot/src/mainboard/sunxi/nezha/bt0)
warning: the feature `int_abs_diff` has been stable since 1.60.0 and no longer requires an attribute to enable
 --> src/soc/src/lib.rs:2:12
  |
2 | #![feature(int_abs_diff)]
  |            ^^^^^^^^^^^^
  |
  = note: `#[warn(stable_features)]` on by default

warning: type alias `PGUART` is never used
  --> src/soc/src/sunxi/d1/uart.rs:19:6
   |
19 | type PGUART = (PG17<Function<7>>, PG18<Function<7>>);
   |      ^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `oreboot-soc` (lib) generated 2 warnings
 Documenting oreboot-nezha-bt0 v0.1.0 (/home/ben/ofw/oreboot/src/mainboard/sunxi/nezha/bt0)
warning: this URL is not a hyperlink
 --> src/mainboard/sunxi/nezha/bt0/src/main.rs:1:1
  |
1 | #![doc = include_str!("README.md")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://github.com/orangecms/linux/tree/5.19-smaeul-plus-dts>`
  |
  = note: bare URLs are not automatically turned into clickable links
  = note: `#[warn(rustdoc::bare_urls)]` on by default

```

4. Make a change to README.md
5. Build docs again and note that Cargo invalidates caches, and builds new Documentation artifacts

Signed-off-by: Ben Werthmann <ben.werthmann@gmail.com>

2022-10-28 03:14 UTC, bwerthmann commented
@orangecms PTAL.

2022-10-28 15:24 UTC, orangecms requested changes

2022-10-28 15:24 UTC, orangecms commented on src/mainboard/sunxi/nezha/README.md
> +https://github.com/orangecms/linux/tree/5.19-smaeul-plus-dts/arch/riscv/boot/dts/allwinner)
More than just the DTS is needed, so the reference was to the branch.

How do you feel about keeping the phrasing as is, adding the Markdown link formatting, and giving the link a title that is the URL again, so it'll be renderd in Rust docs just like on GitHub?
We could improve the wording thereafter.

2022-10-29 00:38 UTC, bwerthmann commented on src/mainboard/sunxi/nezha/README.md
> +#### Notes on Device Tree Blob (DTB)
@orangecms WDYT?

2022-10-29 00:43 UTC, bwerthmann commented
Changes to doc content moved to #616.

2022-10-29 00:44 UTC, bwerthmann commented on src/mainboard/sunxi/nezha/README.md
> +#### Notes on Device Tree Blob (DTB)
#616

2022-10-29 01:55 UTC, bwerthmann commented
@orangecms should be :green_circle: now.

2022-10-29 07:37 UTC, orangecms approved these changes

2022-10-29 07:38 UTC, merged